const mongoose = require("mongoose")            // In mongo DB, data is stored in form of "documents", one document means one
                                                // set of (title, description and userId) in the code below
                                                // We have a collection of these documents.... this collection is called
                                                // "collection"   :) 


const NoteSchema= mongoose.Schema({

    title:{
        type:String,
        required:true
    },

    description:{
        type:String,
        required:true
    },

    userId:{
        type: mongoose.Schema.Types.ObjectId,           // This data-type is data-type of an "auto-generated"
                                                        // property, for each "Schema" an autogenerated property called
                                                        // " _id " is generated, to uniquely identify each document, and the
                                                        // "mongoose.Schema.Types.ObjectId" is the "data-type" of that " _id "
                                                        // property
        ref: "User",                // Referencing to the " _id " of objects "User" collection
                                    // In DB all notes are stored together... to know to which person these notes belong to...
                                    // this ref is important
                                    // So that when accessing the notes, we know which user's notes which is and we don't end up
                                    // showing notes of one person to another..
        required:true
    }

},{timestamps:true})            // timestamps will just add two extra properties in our notes.. that is the time at which our note is
                        // created and time when it is updated..


            // So each note will comprise of :
                // "title" , "description" , "_id" (Unique autogenerated id for each note) , 
                // "userId" (To know which user this note belongs to.. which means "_id" of the user :) )
                // "creation-time", "updation-time", 

module.exports= mongoose.model("Notes", NoteSchema)             // Here "Notes" is the name of this collection

